// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  R315-11
// DateTime: 15.02.2017 17:47:03
// UserName: student
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace SimpleParser
{
public enum Tokens {error=48,
    EOF=49,BEGIN=50,END=51,INUM=52,ID=53,ASSIGN=54,
    SEMICOLON=55,WHILE=56,DOUBLEDOT=57,FOR=58,IF=59,ELSE=60,
    PRINT=61,PRINTLN=62,AND=63,OR=64,LESSER=65,GREATER=66,
    LESSEREQ=67,GREATEREQ=68,EQ=69,NOTEQ=70};

// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<int,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<int, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Ёти объ€влени€ добавл€ютс€ в класс GPPGParser, представл€ющий собой парсер, генерируемый системой gppg
    public Parser(AbstractScanner<int, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[40];
  private static State[] states = new State[78];
  private static string[] nonTerms = new string[] {
      "progr", "$accept", "stlist", "statement", "assign", "block", "while_cycle", 
      "for_cycle", "if", "print", "ident", "expr", "L", "R", "S", "T", "F", };

  static Parser() {
    states[0] = new State(new int[]{53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-1,1,-3,3,-4,77,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[1] = new State(new int[]{49,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{53,21,50,46,56,50,58,54,59,62,61,69,62,73,49,-2},new int[]{-4,4,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[4] = new State(-4);
    states[5] = new State(new int[]{55,6});
    states[6] = new State(-5);
    states[7] = new State(new int[]{54,8});
    states[8] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,9,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[9] = new State(new int[]{64,10,55,-12});
    states[10] = new State(new int[]{53,21,52,22,40,23},new int[]{-13,11,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[11] = new State(new int[]{63,12,64,-14,55,-14,41,-14,53,-14,50,-14,56,-14,58,-14,59,-14,61,-14,62,-14});
    states[12] = new State(new int[]{53,21,52,22,40,23},new int[]{-14,13,-15,44,-16,35,-17,34,-11,20});
    states[13] = new State(new int[]{69,14,70,28,65,36,66,38,67,40,68,42,63,-16,64,-16,55,-16,41,-16,53,-16,50,-16,56,-16,58,-16,59,-16,61,-16,62,-16});
    states[14] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,15,-16,35,-17,34,-11,20});
    states[15] = new State(new int[]{43,16,45,30,69,-18,70,-18,65,-18,66,-18,67,-18,68,-18,63,-18,64,-18,55,-18,41,-18,53,-18,50,-18,56,-18,58,-18,59,-18,61,-18,62,-18});
    states[16] = new State(new int[]{53,21,52,22,40,23},new int[]{-16,17,-17,34,-11,20});
    states[17] = new State(new int[]{42,18,47,32,43,-25,45,-25,69,-25,70,-25,65,-25,66,-25,67,-25,68,-25,63,-25,64,-25,55,-25,41,-25,53,-25,50,-25,56,-25,58,-25,59,-25,61,-25,62,-25,57,-25});
    states[18] = new State(new int[]{53,21,52,22,40,23},new int[]{-17,19,-11,20});
    states[19] = new State(-28);
    states[20] = new State(-30);
    states[21] = new State(-11);
    states[22] = new State(-31);
    states[23] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,24,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[24] = new State(new int[]{41,25,64,10});
    states[25] = new State(-32);
    states[26] = new State(new int[]{63,12,64,-13,55,-13,41,-13,53,-13,50,-13,56,-13,58,-13,59,-13,61,-13,62,-13});
    states[27] = new State(new int[]{69,14,70,28,65,36,66,38,67,40,68,42,63,-15,64,-15,55,-15,41,-15,53,-15,50,-15,56,-15,58,-15,59,-15,61,-15,62,-15});
    states[28] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,29,-16,35,-17,34,-11,20});
    states[29] = new State(new int[]{43,16,45,30,69,-19,70,-19,65,-19,66,-19,67,-19,68,-19,63,-19,64,-19,55,-19,41,-19,53,-19,50,-19,56,-19,58,-19,59,-19,61,-19,62,-19});
    states[30] = new State(new int[]{53,21,52,22,40,23},new int[]{-16,31,-17,34,-11,20});
    states[31] = new State(new int[]{42,18,47,32,43,-26,45,-26,69,-26,70,-26,65,-26,66,-26,67,-26,68,-26,63,-26,64,-26,55,-26,41,-26,53,-26,50,-26,56,-26,58,-26,59,-26,61,-26,62,-26,57,-26});
    states[32] = new State(new int[]{53,21,52,22,40,23},new int[]{-17,33,-11,20});
    states[33] = new State(-29);
    states[34] = new State(-27);
    states[35] = new State(new int[]{42,18,47,32,43,-24,45,-24,69,-24,70,-24,65,-24,66,-24,67,-24,68,-24,63,-24,64,-24,55,-24,41,-24,53,-24,50,-24,56,-24,58,-24,59,-24,61,-24,62,-24,57,-24});
    states[36] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,37,-16,35,-17,34,-11,20});
    states[37] = new State(new int[]{43,16,45,30,69,-20,70,-20,65,-20,66,-20,67,-20,68,-20,63,-20,64,-20,55,-20,41,-20,53,-20,50,-20,56,-20,58,-20,59,-20,61,-20,62,-20});
    states[38] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,39,-16,35,-17,34,-11,20});
    states[39] = new State(new int[]{43,16,45,30,69,-21,70,-21,65,-21,66,-21,67,-21,68,-21,63,-21,64,-21,55,-21,41,-21,53,-21,50,-21,56,-21,58,-21,59,-21,61,-21,62,-21});
    states[40] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,41,-16,35,-17,34,-11,20});
    states[41] = new State(new int[]{43,16,45,30,69,-22,70,-22,65,-22,66,-22,67,-22,68,-22,63,-22,64,-22,55,-22,41,-22,53,-22,50,-22,56,-22,58,-22,59,-22,61,-22,62,-22});
    states[42] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,43,-16,35,-17,34,-11,20});
    states[43] = new State(new int[]{43,16,45,30,69,-23,70,-23,65,-23,66,-23,67,-23,68,-23,63,-23,64,-23,55,-23,41,-23,53,-23,50,-23,56,-23,58,-23,59,-23,61,-23,62,-23});
    states[44] = new State(new int[]{43,16,45,30,69,-17,70,-17,65,-17,66,-17,67,-17,68,-17,63,-17,64,-17,55,-17,41,-17,53,-17,50,-17,56,-17,58,-17,59,-17,61,-17,62,-17});
    states[45] = new State(-6);
    states[46] = new State(new int[]{53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-3,47,-4,77,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[47] = new State(new int[]{51,48,53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-4,4,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[48] = new State(-33);
    states[49] = new State(-7);
    states[50] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,51,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[51] = new State(new int[]{64,10,53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-4,52,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[52] = new State(-34);
    states[53] = new State(-8);
    states[54] = new State(new int[]{53,55});
    states[55] = new State(new int[]{54,56});
    states[56] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,57,-16,35,-17,34,-11,20});
    states[57] = new State(new int[]{57,58,43,16,45,30});
    states[58] = new State(new int[]{53,21,52,22,40,23},new int[]{-15,59,-16,35,-17,34,-11,20});
    states[59] = new State(new int[]{43,16,45,30,53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-4,60,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[60] = new State(-35);
    states[61] = new State(-9);
    states[62] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,63,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[63] = new State(new int[]{64,10,53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-4,64,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[64] = new State(new int[]{60,65,53,-36,50,-36,56,-36,58,-36,59,-36,61,-36,62,-36,49,-36,51,-36});
    states[65] = new State(new int[]{53,21,50,46,56,50,58,54,59,62,61,69,62,73},new int[]{-4,66,-5,5,-11,7,-6,45,-7,49,-8,53,-9,61,-10,67});
    states[66] = new State(-37);
    states[67] = new State(new int[]{55,68});
    states[68] = new State(-10);
    states[69] = new State(new int[]{40,70});
    states[70] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,71,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[71] = new State(new int[]{41,72,64,10});
    states[72] = new State(-38);
    states[73] = new State(new int[]{40,74});
    states[74] = new State(new int[]{53,21,52,22,40,23},new int[]{-12,75,-13,26,-14,27,-15,44,-16,35,-17,34,-11,20});
    states[75] = new State(new int[]{41,76,64,10});
    states[76] = new State(-39);
    states[77] = new State(-3);

    rules[1] = new Rule(-2, new int[]{-1,49});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{-3,-4});
    rules[5] = new Rule(-4, new int[]{-5,55});
    rules[6] = new Rule(-4, new int[]{-6});
    rules[7] = new Rule(-4, new int[]{-7});
    rules[8] = new Rule(-4, new int[]{-8});
    rules[9] = new Rule(-4, new int[]{-9});
    rules[10] = new Rule(-4, new int[]{-10,55});
    rules[11] = new Rule(-11, new int[]{53});
    rules[12] = new Rule(-5, new int[]{-11,54,-12});
    rules[13] = new Rule(-12, new int[]{-13});
    rules[14] = new Rule(-12, new int[]{-12,64,-13});
    rules[15] = new Rule(-13, new int[]{-14});
    rules[16] = new Rule(-13, new int[]{-13,63,-14});
    rules[17] = new Rule(-14, new int[]{-15});
    rules[18] = new Rule(-14, new int[]{-14,69,-15});
    rules[19] = new Rule(-14, new int[]{-14,70,-15});
    rules[20] = new Rule(-14, new int[]{-14,65,-15});
    rules[21] = new Rule(-14, new int[]{-14,66,-15});
    rules[22] = new Rule(-14, new int[]{-14,67,-15});
    rules[23] = new Rule(-14, new int[]{-14,68,-15});
    rules[24] = new Rule(-15, new int[]{-16});
    rules[25] = new Rule(-15, new int[]{-15,43,-16});
    rules[26] = new Rule(-15, new int[]{-15,45,-16});
    rules[27] = new Rule(-16, new int[]{-17});
    rules[28] = new Rule(-16, new int[]{-16,42,-17});
    rules[29] = new Rule(-16, new int[]{-16,47,-17});
    rules[30] = new Rule(-17, new int[]{-11});
    rules[31] = new Rule(-17, new int[]{52});
    rules[32] = new Rule(-17, new int[]{40,-12,41});
    rules[33] = new Rule(-6, new int[]{50,-3,51});
    rules[34] = new Rule(-7, new int[]{56,-12,-4});
    rules[35] = new Rule(-8, new int[]{58,53,54,-15,57,-15,-4});
    rules[36] = new Rule(-9, new int[]{59,-12,-4});
    rules[37] = new Rule(-9, new int[]{59,-12,-4,60,-4});
    rules[38] = new Rule(-10, new int[]{61,40,-12,41});
    rules[39] = new Rule(-10, new int[]{62,40,-12,41});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 30: // F -> ident
{ CurrentSemanticValue = new IdNode(ValueStack[ValueStack.Depth-1] as string); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
